### ISSUE TITLE
Write a webapp to do the scoring of the BAT

### ISSUE THREAD

**Issue by MarquisAlx** [BilingualAphasia/AndroidBilingualAphasiaTest#2]
Export data

**Comment by cesine** [comment]
More information:

Needed: Export data with a comparison to norms so that test administrator can get a quick idea of patients skills in BAT sections (some sort of visual graph would be ideal)

*This depends on having norming data. There are existing norming data collected when the English and French BATs were adapted. This data might be findable. 
*This depends on having a scoring script which scores each section of the BAT. There is an existing program somewhere which may be reverse engineered... if it can be found. 

For more information on how to make the scoring script see Paradis 2011

**Comment by cesine** [comment]
we have received the original scoring programs from Dr Paradis, need to see how much we can access in them or if we can find a compute that can run them

**Comment by cesine** [comment]
It's official, we have a wee bit of left over BAT money to write a little scoring WebApp that will let the test administrator enter the data, and then return the results to them saying what percentile the participant scored for the  areas of the test. 

If anyone wants to take this on, simply write us a message and we will assign this Issue to you.

We might consider calling it the WebAppBAT (following original naming conventions PCBAT, MACBAT)

Here is the original readme file for the scoring section of the PCBAT

```
 Scoring

    The most important thing to remember when entering
 responses is that items which are  left blank are effectively
 ignored when scores are calculated. Thus, an item should be
 left blank  only when it has not been administered to a given
 subject, or when the item is to be disregarded  for some
 reason (e.g., the response is missing or cannot be
 determined). A response of "0", on the  other hand, is
 available as a choice on most items, and it indicates that
 the subject gave no  response when the item was administered.
 To illustrate the difference for purposes of scoring, a
 section of ten items all of which were left blank would
 receive a score of 0/0, while ten  responses of "0" would
 give 0/10.
    The score files created by PCBAT contain scores for
 sections 2-31 (Part B) or 33-42 (Part  C) of the BAT, as well
 as a matrix which breaks down the scores by the linguistic
 levels  (Phonology, Morphology, Lexicon, Syntax, and
 Semantics for Part B; Morphology/Syntax and  Lexicon for Part
 C) and skills (Comprehension, Repetition, Judgment, Lexical
 Access,  Propositionalizing, Reading, and Writing for Part B;
 Translation and Grammaticality Judgment  for Part C) tapped
 in each section. All of these scores are given in fractional
 and decimal form.  (In decimal scores, "N/A" corresponds to a
 score of 0/0.) An example of the matrix of scores is  shown
 below:

SCORES BY LINGUISTIC LEVEL AND SKILL  
 0/0     1/1     0/0     0/0     0/0     0/0     0/0   Phonlgy   1/1
 0/0     0/0     0/0     0/0     0/0     0/0     0/0   Mrphlgy   0/0
 0/2     7/7     0/0     0/0     2/2     0/2     0/0   Lexicon   9/13
 8/10    1/1     2/2    14/14    0/0     0/0     0/0   Syntax   25/27
 0/0     0/0     0/0     0/0     0/0     0/0     0/0   Smntics   0/0
 Compreh Repetit Judgmnt LxclAcc Proposi Reading Writing
 8/12    9/9     2/2    14/14    2/2     0/2     0/0

 Each cell in the matrix gives a score for a combination of
 linguistic level and skill - for  example, the score in the 
 top left corner of the matrix is for phonological 
 comprehension. The  rightmost column gives the total scores 
 for the five linguistic levels, and the bottom row gives  the 
 totals for the seven linguistic skills.     
```

**Comment by cesine** [comment]
We received chapter 2, 3 and the crucial tables for the scoring program. The scanned tables which were uploaded into the documentation directory:

https://github.com/iLanguage/AndroidBilingualAphasiaTest/blob/master/documentation/Paradis,Libben-1987-Assessment_of_Bilingual_Aphasia-Scoring_tables_2.1_and_2.2.PDF?raw=true

I recommend designing a google spreadsheet for use in calculating the scoring and sharing it with the team, once we have decided on the spreadsheet format we can work on automating the data entry (ie, this issue2, making a webapp that communicates with the spreadsheet).

**Comment by cesine** [comment]
Google Spreadsheets has user friendly forms to do data input
https://docs.google.com/spreadsheet/viewform?formkey=dHZZcEw1MWh6X1Y4VXJkQ0E2dl9GblE6MQ
Here is the source of the above form:
https://docs.google.com/spreadsheet/ccc?key=0AjJz4n1qwkYAdHZZcEw1MWh6X1Y4VXJkQ0E2dl9GblE#gid=0

(and for posterity, here is a link to the results format that the tablet currently produces; https://docs.google.com/spreadsheet/ccc?key=0AjJz4n1qwkYAdFVDSmtmRnJDQl80cmlMYk1KZzM0N1E&hl=en_US#gid=2)

**Comment by cesine** [comment]
Following the decision to keep naming convetions from the ancient apps (since they were good conventions) the OprimeAdministrator is now depreciated, and will be using this repo from now on:

https://github.com/iLanguage/WebAppBilingualAphasiaTest/

**Comment by cesine** [comment]
This issue is being worked on in a seperate repository: 

https://github.com/iLanguage/BilingualAphasiaTestScorer
