### ISSUE TITLE
Entrer des questions du BAT dans le google spreadsheet

### ISSUE THREAD

**Issue by cesine** [BilingualAphasia/AndroidBilingualAphasiaTest#23]
Click on this link to edit the form and add more items from the BAT test book https://docs.google.com/spreadsheet/ccc?key=0AjJz4n1qwkYAdHZZcEw1MWh6X1Y4VXJkQ0E2dl9GblE#gid=0 )

**Comment by cesine** [comment]
@emiedess voici le lien pour le issue tracker

**Comment by cesine** [comment]
Voici le lien pour le BAT en format pdf 
https://secureweb.mcgill.ca/linguistics/sites/mcgill.ca.linguistics/files/english_bat.pdf

**Comment by MarquisAlx** [comment]
Il y'aura parties C a enter aussi qui est moins une priorite

https://secureweb.mcgill.ca/linguistics/sites/mcgill.ca.linguistics/files/English-French.pdf

**Comment by MarquisAlx** [comment]
Ajouter les chiffres correspondant aux questions devant chaque question

**Comment by MarquisAlx** [comment]
I unsuccessfully tried to add the following to github (ok I guess I need a
tutorial)
the answers for many questions are 3 way not 2: +, -, 0

2012/3/23 cesine <
reply@reply.github.com

**Comment by MarquisAlx** [comment]
I looked and didn't find a way to collapse multiple spreadsheet

**Comment by emiedess** [comment]
Bonjour!  
on se voit à notre rendez-vous habituel ce vendredi le 27 avril ??   J'ai hâte de continuer le projet!

**Comment by cesine** [comment]
a ce vendredi :)

**Comment by cesine** [comment]
this was finished a month ago
