### ISSUE TITLE
Prepare one suite of videos for Train new language model using data collected from BilingualAphasiaTest participants

### ISSUE THREAD

**Issue by cesine** [BilingualAphasia/AndroidBilingualAphasiaTest#41]
@zazoo est en train de transcire des videos de une de nos participant en utilsant des video Privee de YouTube. Elle a fait une repository ici

https://github.com/zazoo/TranscriptionDesVideosDeBAT

**Comment by cesine** [comment]
on etait pas capable de partager des permission de corrige des sutitre sur youtube. la prochaine fois on va essayer google docs pour que plus qu'une personne aura de lacces au sutitres. voici un peux plus d'information
https://support.google.com/docs/bin/answer.py?hl=en&answer=1372218&topic=1360908&ctx=topic

**Comment by zazoo** [comment]
Voici le lien vers le sous-projet par rapport a la transcription audio des videos
https://github.com/zazoo/TranscriptionDesVideosDeBAT
