### ISSUE TITLE
add retroaction when we touch

### ISSUE THREAD

**Issue by MarquisAlx** [BilingualAphasia/AndroidBilingualAphasiaTest#48]
add retroaction when we touch (e.g. in syntactic comprehension)

**Comment by cesine** [comment]
it turns out this was added in version 1.0, but still needs to be added in for version 2.0

**Comment by cesine** [comment]
@zazoo, look for "MediaPlayer" in the StoryBookSubExperiment. We should be able to play a sound when the user touches an image

**Comment by zazoo** [comment]
done!
