### ISSUE TITLE
refactor oprime to use the upstream curl lib

### ISSUE THREAD

**Issue by skattoju-zz** [BilingualAphasia/AndroidBilingualAphasiaTest#53]

**Comment by cesine** [comment]
@skattoju  for now i took page curl out completely.. let me know if you do any more on it. the good news is that we are launched: https://play.google.com/store/apps/details?id=ca.ilanguage.bilingualaphasiatest

**Comment by skattoju-zz** [comment]
sweet!

I see you switched to another pager ... I managed to get upstream page curl working as I library but I was not sure if the pages were in order... I might download your latest changes and submit a pull request with page curl if I get it to work correctly.

P.S.: I put android on my old netbook so I have a tablet with a keyboard and no touch screen. :P

**Comment by cesine** [comment]
we might try putting android on our netbooks too.. you should bring it over
someday so i can see what it is like!

On Wed, Jun 13, 2012 at 1:21 PM, Siddhartha Kattoju <
reply@reply.github.com
