### ISSUE TITLE
***L'application nouvelle version semble marcher uniquement en francais, meme si on choisis une autre langue***

### ISSUE THREAD

**Issue by cesine** [BilingualAphasia/AndroidBilingualAphasiaTest#68]

**Comment by cesine** [comment]
@emiedess j'ai besoin de plus d'informaiotn, quel version de Android, quel appareil? Les langues fonctionne sur toute les android que j'ai essaye (Android 2.1, 2.2, 2.3, 3.0, 4.0.3)

**Comment by zazoo** [comment]
On vient de vérifier l'app et on a remarqué qu'il y a un bug quand on prend une autre langue. En effet, il y a 2 façons pour sélectionner/changer une langue mais 1 seule option fonctionne correctement.

**Comment by cesine** [comment]
j'ai pas pu repliquer le bug. on peux choisir une langue au debut, et on peux le changer en tout temps en clickant sur le bouton pour "menu"
