### ISSUE TITLE
Need light text backgound on the touch visualizer so we can see it

### ISSUE THREAD

**Issue by fieldlinguist** [BilingualAphasia/AndroidBilingualAphasiaTest#7]
in the touch visualizer we cant see all the details when we click on a participants touch dot because the writing is dark, and the picture is drawn with black lines. maybe you could make a light background for the text when we click.

**Comment by cesine** [comment]
added a light rectangle behind the text

```
      ctx.fillStyle = "white";
      var topx = responses[k].labelx+10;
      var topy = responses[k].labely-20;
      ctx.fillRect(topx, topy, 250, 30);

      ctx.fillStyle = responses[k].color;
```

https://github.com/iLanguage/OPrimeAdministrator/commit/1bff854fc7b6cbd6430b8bd9319fedfa6c9db84d
